### ISSUE TITLE
canopy and impervious datasets no longer work with get_nlcd

### ISSUE THREAD

**Issue by mcwoody** [ropensci/FedData#102]
It looks like canopy and impervious were removed as dataset options in get_nlcd (line 47) with the updates made for v4.0.0.

**Comment by YoJimboDurant** [comment]
Hi Woody - you can backgrade your feddata package to 3.0.5:  `devtools::install_github("ropensci/FedData@7786bf1")`

**Comment by bocinsky** [comment]
Hi @mcwoody . Sorry for this... should be fixed now, but let me know if it keeps giving you issues. Thanks!
