### ISSUE TITLE
FedData:::esri_query() failing in FedData 4.0.0

### ISSUE THREAD

**Issue by kevinwolz** [ropensci/FedData#103]
Since upgraded to 4.0.0, with any geometry I try, both `FedData::get_wbd` and `FedData::get_nhd` are failing with the same error caused by `FedData:::esri_query`.

```
<error/purrr_error_indexed>
Error in `purrr::map()`:
ℹ In index: 1.
ℹ With name: WBDHU12.
Caused by error in `magrittr::extract2()`:
! subscript out of bounds
---
Backtrace:
     ▆
  1. ├─FedData::get_wbd(...)
  2. │ └─... %>% magrittr::extract2(1)
  3. ├─FedData:::esri_query(., geom = template, layers = "WBDHU12")
  4. │ └─layer_ids %>% ...
  5. └─purrr::map(...)
  6.   └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  7.     ├─purrr:::with_indexed_errors(...)
  8.     │ └─base::withCallingHandlers(...)
  9.     ├─purrr:::call_with_cleanup(...)
 10.     └─FedData (local) .f(.x[[i]], ...)
 11.       └─... %>% magrittr::extract2("objectIds")
```

**Comment by bocinsky** [comment]
I believe this was fixed in commit [8d64b29](https://github.com/ropensci/FedData/commit/8d64b29a24a36f564462661c510b02d1cf2192b7). Can you give it a go and confirm?

**Comment by kevinwolz** [comment]
I'm now getting this error for `FedData::get_nhd`:
![image](https://github.com/ropensci/FedData/assets/11711566/6cb003ec-e261-4bc6-af0f-96dee207c0dd)

**Comment by bocinsky** [comment]
This was all working earlier this afternoon, but something seems really wacked with the services right now. I'm getting results like every 6th try or so. Hoping they are just doing updates or something and that it comes back available in the morning.

**Comment by bocinsky** [comment]
Their ArcGIS servers are still struggling as of now. For reference, FedData is querying several of the NHD (and NHDPlus) layers from here:

<https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer>

You'll notice that we are getting HTTP 500s randomly when selecting a layer. Hoping this stabilized soon...

**Comment by kevinwolz** [comment]
@bocinsky have you tested this again recently? Have things stablized?

**Comment by bocinsky** [comment]
Hey @kevinwolz. It appears to be back up and running. Just ran my tests and things are working as expected. Would you mind confirming on your end?

**Comment by bocinsky** [comment]
Well, spoke too soon. Definitely more stable than over the weekend, but the ArcGIS MapServer is still having issues every once in a while. I don't think there is much that can be done on our (FedData) end on this, so I'm closing for now.

**Comment by kevinwolz** [comment]
@bocinsky thoughts?
