### ISSUE TITLE
NLCD 2021 now available - fully supported?

### ISSUE THREAD

**Issue by kevinwolz** [ropensci/FedData#105]
The 2021 NLCD data was released in July 2023. It seems that `FedData::get_nlcd()` brings this in just fine when `year = 2021` in the few tests that I have done. However, since the function documentation does not mention 2021, I wanted to check to make sure that 2021 is robustly supported.

**Comment by bocinsky** [comment]
Thanks @kevinwolz! Just pushed a patch, and running checks for CRAN submission.
