### ISSUE TITLE
"Tree Canopy" dataset name changed

### ISSUE THREAD

**Issue by zxy1219** [ropensci/FedData#107]
I ran this code to get tree canopy data:

tc_2016 <-
  get_nlcd(
    as(sfc_station, "Spatial"),
    dataset = "canopy",
    label = "canopy",
    extraction.dir = paste(rootDir, "preprocessed_data", sep = "/"),
    force.redo = T,
    year = 2016
  )

I got an error message:
"**Error in get_nlcd(as(sfc_station, "Spatial"), dataset = "canopy", label = "canopy",  : 
  No web coverage service at https://www.mrlc.gov/geoserver/mrlc_download/NLCD_2016_Tree_Canopy_L48/wcs. See available services at https://www.mrlc.gov/geoserver/ows?service=WCS&version=2.0.1&request=GetCapabilities**
"

Then I go to the link in the error message. I think the name of the tree canopy data is no longer "NLCD_XXXX_Tree_Canopy" for CONUS US. The current name for those data is: "nlcd_tcc_conus_XXXX_v2021-4 ". The "XXXX" is the year indicating the data version.

**Comment by bocinsky** [comment]
Hi there. Sorry for the delayed response... I believe this was fixed in the latest update to FedData. Please update your installation and let me know whether your problem persists:

```{r}
update.packages("FedData")
```
