### ISSUE TITLE
Error in article

### ISSUE THREAD

**Issue by maelle** [ropensci/FedData#108]
Via https://ropensci.r-universe.dev/builds we see a failure for the article, locally I get this error:

```r
Quitting from lines 128-144 [GHCN-precipitation] (FedData.Rmd)
                                                                                                               
Error:
! FlatGeobuf driver not available in supported drivers, see `st_drivers()'
Backtrace:
 1. FedData::get_ghcn_daily(...)
 3. sf::write_sf(., dsn = raw_inventory)
 5. sf:::st_write.sf(..., quiet = quiet, append = append, delete_layer = delete_layer)
 6. sf:::guess_driver_can_write(dsn)
Execution halted

```

**Comment by bocinsky** [comment]
Hmm, support for FlatGeoBuf is built into GDAL >= v3.1. The current release of GDAL is v3.8.1. Would you mind confirming what version of GDAL you have installed on your build machine? My guess is that I should up the system requirement to GDAL (>= 3.1.0), as FedData is now storing the GHCN station inventory as a FlatGeoBuf file.

**Comment by maelle** [comment]
@jeroen any insight? Thanks!

**Comment by jeroen** [comment]
We the libraries that are included with ubuntu-22.04.

**Comment by maelle** [comment]
@bocinsky friendly reminder (tricky if you can't reproduce it) :smile_cat:

**Comment by bocinsky** [comment]
I think this is working now, but we'll see if it stays that way!

**Comment by maelle** [comment]
Indeed, thank you!!
