### ISSUE TITLE
get_daymet returns purr error when using run example

### ISSUE THREAD

**Issue by rsmiller74** [ropensci/FedData#112]
get_daymet returning error below when using run example. 

> DAYMET <- FedData::get_daymet(
   template = FedData::meve,
   label = "meve",
   elements = c("prcp", "tmin", "tmax"),
   years = 1980:1985
 )

Error in `purrr::map()`:
i In index: 1.
i With name: prcp.
Caused by error:
! error in evaluating the argument 'x' in selecting a method for function 'rast': i In index: 1.
i With name: 1980.
Caused by error in `download_daymet_thredds()`:
! Problem creating coverage [prcp].
Run `rlang::last_trace()` to see where the error occurred.

> packageVersion("FedData")
[1] ‘4.0.1’

> packageVersion("purrr")
[1] ‘1.0.2’

**Comment by bocinsky** [comment]
This seems to have resolved itself... I looked into the Daymet THREDDS server the other day, and the netcdf subset service was down. Just ran the example, and it worked on my end, so I think they got the TDS back up.
