### ISSUE TITLE
Unable to install dev version after updating to R version 4.4.1 (dependency issue)

### ISSUE THREAD

**Issue by monikashea** [ropensci/FedData#118]
I recently updated R to version 4.4.1 and while reinstalling packages I was initially unable to install the dev version of FedData:

```remotes::install_github("ropensci/FedData", dependencies = FALSE)```

gave the error:

```ERROR: dependencies 'arcgislayers', 'ncdf4' are not available for package 'FedData'```

I was able to get `"ncdf4"` but `"arcgislayers"` would not install. I looked at their [github issues](https://github.com/R-ArcGIS/arcgislayers/issues/217) and found that the package is not available for the newest R version. Following the responses in the issue, I was able to install the package from r-universe using:

```install.packages("arcgis", repos = "https://r-arcgis.r-universe.dev")```

Once I did that, I was able to get FedData installed.

**Comment by JosiahParry** [comment]
I am sorry you are running into this issue. I've been working to get this fixed but the package {arcpbf} has been pending CRAN review for 7 days now https://cran.r-project.org/incoming/pending/. That package needs to be published before {arcgislayers} can be published again.

**Comment by bocinsky** [comment]
FedData is back in the queue for CRAN review. Sorry for the hassle!
