### ISSUE TITLE
CRAN resubmission?

### ISSUE THREAD

**Issue by jpiaskowski** [ropensci/FedData#120]
Hello, this package is part of the [agricultural CRAN task view](https://cran.r-project.org/view=Agriculture) and it looks like it was recently removed from CRAN. Is there a plan to resubmit this? Thank you.

**Comment by bocinsky** [comment]
Hi Julia! Thanks for reaching out. We will indeed be resubmitting it… it was removed due to an upstream dependency being removed, but that has been sorted out and FedData will hopefully return to CRAN soon.

Cheers!

**Comment by jpiaskowski** [comment]
Fantastic, thank you.

**Comment by bocinsky** [comment]
FedData 4.1.0 on CRAN now! 

<https://cran.r-project.org/package=FedData>
