### ISSUE TITLE
Annual NLCD - a new database

### ISSUE THREAD

**Issue by Rapsodia86** [ropensci/FedData#121]
Greetings! 
Any plans to add the new Annual NLCD: https://www.usgs.gov/centers/eros/science/nlcd-product-suite?

Thanks,
Monika

**Comment by bocinsky** [comment]
This is awesome, and way more accessible (via COGs on AWS) than the legacy product. I've been adding it today, and will push an update tomorrow morning.

**Comment by Rapsodia86** [comment]
Great! 
Thank you!
