### ISSUE TITLE
Integration of new "Annual NLCD" data

### ISSUE THREAD

**Issue by kevinwolz** [ropensci/FedData#123]
I'm excited by USGS's announcement of the new ["Annual NLCD"](https://www.usgs.gov/centers/eros/science/about-annual-nlcd) dataset. @bocinsky do you have any plans to incorporate these data into FedData?

If they are using the same web service, perhaps this could be as simple as allowing more possible values for the `year` argument. I doubt that's the case, though.

**Comment by bocinsky** [comment]
Hi @kevinwolz. The annual NLCD is already in FedData! Check out `?get_nlcd_annual`. Enjoy!

**Comment by kevinwolz** [comment]
Amazing! Thanks for being a step ahead. I just integrated it seamlessly into our workflow.
