### ISSUE TITLE
Plans for the NLCD?

### ISSUE THREAD

**Issue by jhollist** [ropensci/FedData#22]
Just discovered FedData today!  Very nice.  

Any plans to include functions for getting the National Land Cover Dataset?  I'll admit to not knowing too much about the APIs available to access it so don't even know if it is possible.  I believe the National Map REST services to provide access.

Again, nice job and thanks!

**Comment by bocinsky** [comment]
Hey Jeffrey,

Thanks for the comment, and for checking out FedData. I will definitely add the NLCD to my list!

**Comment by jhollist** [comment]
@bocinsky Cool!  If you want some help with it let me know.  It is something I've wanted to play around with and might be able to carve out some time in the next couple of months.  In the meantime, I'll dig into FedData some more to get familiar with your implementation.

**Comment by bocinsky** [comment]
Hi @jhollist. After a long delay, I've been digging into the NLCD a bit. Do you know of a good (i.e., *fast*) subset service for the NLCD that can be accessed through an API? I'm having trouble finding one.

**Comment by jhollist** [comment]
Funny you sent this today...  We've been working on this very thing and were at the point of deciding if we wanted to include it in the package we are working on or suggest an addition to FedData.  At this point we don'r have any strong opinions on which way to go.

In any event, there aren't any good (i.e. *fast*) APIs that I know of.  That being said there has been some improvements in availability of the data through [USGS Sciencebase]( https://www.sciencebase.gov/catalog/item/4f70a43ce4b058caae3f8db3).  The data are available for each year (2001,2006, 2011) are tiled in 1degree tiles, and served from S3 (e.g. <https://s3-us-west-2.amazonaws.com/prd-tnm/StagedProducts/NLCD/data/2011/impervious/3x3/NLCD2011_IMP_N36W105.zip>).    Our plan was to use an `sf` object as input and grab the overlapping NLCD tiles, merge those, and reproject to the input sf CRS.

We have a bit of a start on it, but would be happy to chat about including it in FedData if that makes the most sense.

**Comment by bocinsky** [comment]
Hitting Sciencebase seems perfectly reasonable until a bespoke subset service becomes available (and perhaps in lieu of one, even then). If y’all include it in your package, I’ll probably just wrap your function in a FedData-like function call (`get_nlcd`) for simplicity’s sake. I’m also happy to include it in FedData if y’all would prefer that. I had started working on a tool that extracts raster data stored on Google Earth Engine, but that’s probably beyond the scope of providing simple access to the NLCD from within R.

The long-term plan for FedData is to move entirely towards simple features and tidy data structures, so glad to hear you are going in that direction too!

**Comment by jhollist** [comment]
Sound good.  We will keep hacking on the function and will let you know when we have it working.  FYI, the package (in VERY early stage) is [`goatscape`](https://github.com/usepa/goatscape).

And agreed on `sf`/tidy.  Makes the whole process a lot more pleasant.  Is the plan for FedData v3 to be `sf`/tidy based?

**Comment by bocinsky** [comment]
Yep, entire rewrite. sf/tidyverse/[stars](https://github.com/r-spatial/stars) and using remote services when available (primarily access to the USDA soils API via the [`soildb`](https://github.com/ncss-tech/soilDB) package). I'll also define tidy classes for each type of data available through FedData, so that similar data types (e.g., interpolated weather data from PRISM or daymet) have the same class.

**Comment by bocinsky** [comment]
Just have to track down some funding to support dev time. :-)

**Comment by bocinsky** [comment]
Hey @jhollist!

Alright, I ended up adding NLCD coverage to FedData today, because I needed to do it anyway for another project. It is still FedData2-esque (no `sf` support), but gets the job done. It's up on Github, and heading towards CRAN. Please let me know if you try it out, and if you have any suggestions for it!

Best,
Kyle
