### ISSUE TITLE
Changes in soilDB::SDA_query() and FedData test suite

### ISSUE THREAD

**Issue by dylanbeaudette** [ropensci/FedData#32]
Hi Kyle,

I received the following news after submitting a major update of the soilDB package to CRAN:

```
Check: tests
New result: ERROR
     Running ‘testthat.R’ [6s/31s]
   Running the tests in ‘tests/testthat.R’ failed.
   Complete output:
     > library(testthat)
     > library(FedData)
     Loading required package: sp
     >
     > test_check("FedData")

     Attaching package: 'curl'

     The following object is masked from 'package:httr':

         handle_reset

     Loading required package: aqp
     This is aqp 1.15
     1. Failure: The SoilDB data queries work (@test.SSURGO.R#21) 
-------------------
     soilDB::SDA_query(q) did not throw an error.



     Attaching package: 'raster'

     The following objects are masked from 'package:aqp':

         metadata, metadata<-

     testthat results 
================================================================
     OK: 24 SKIPPED: 0 FAILED: 1
     1. Failure: The SoilDB data queries work (@test.SSURGO.R#21)

     Error: testthat unit tests failed
     Execution halted
```

Please note that `SDA_query()` now attempts to be a little smarter about errors, reporting SQL syntax errors, and returning multi-table results. See the manual page for the function in the [development version](https://github.com/ncss-tech/soilDB). Some of these changes are [documented in related issues](https://github.com/ncss-tech/soilDB/issues?utf8=%E2%9C%93&q=SDA).

Thanks!
Dylan

**Comment by bocinsky** [comment]
The soilDB::SDA_query does not throw an error anymore when requesting data from a non-existent soil survey area; it now returns a NULL object. Changed the test to expect a NULL. Running checks on Winbuilder and resubmitting to CRAN. Thanks @dylanbeaudette!

**Comment by dylanbeaudette** [comment]
Thanks Kyle!
