### ISSUE TITLE
nlcd_tiles not found when using ::

### ISSUE THREAD

**Issue by jhollist** [ropensci/FedData#34]
The following example 
```
vepPolygon <- FedData::polygon_from_extent(raster::extent(672800, 740000, 4102000, 4170000),                                          proj4string = "+proj=utm +datum=NAD83 +zone=12")

NLCD <- FedData::get_nlcd(template = vepPolygon, year = 2011, dataset = "landcover", label = "VEPIIN")
```
returns
```
Error in methods::extends(class(x), "BasicRaster") : 
  object 'nlcd_tiles' not found
In addition: Warning message:
In data(nlcd_tiles, envir = environment()) :
  data set ‘nlcd_tiles’ not found
```
But works fine if using library(FedData) instead of `::`.

Didn't have time to dig into this too much more.

**Comment by bocinsky** [comment]
Just pushed a fix. `get_ncld` (and `get_daymet`) were trying to load internal data files from the user's environment. Should work now (the dev version). Will push to cran once a few more fixes accumulate.

**Comment by jhollist** [comment]
Well now this is service!  Thanks @bocinsky!

**Comment by bocinsky** [comment]
Thanks for catching it and submitting an issue!
