### ISSUE TITLE
get_nlcd for dataset = "canopy" not working for year = 2001 or 2006; works for 2011

### ISSUE THREAD

**Issue by willbmisled** [ropensci/FedData#38]
Hi I'm using your FedData package to download the NLCD data.  It works great for the landcover and impervious datasets but I'm having trouble using it for canopy.  Canopy works fine for year = 2011 but fails for 2006 and 2001.  The example on your github page works fine (see below).

vepPolygon <- FedData::polygon_from_extent(raster::extent(672800, 740000, 4102000, 4170000),
                                  proj4string = "+proj=utm +datum=NAD83 +zone=12")

NLCD_canopy <- get_nlcd(template = vepPolygon, year = 2011, dataset = "canopy", label = "V11") #  works
...
But if I change the year to 2006 (or 2001) I get the following error message:  

NLCD_canopy <- get_nlcd(template = vepPolygon, year = 2006, dataset = "canopy", label = "V06")

Area of interest includes 1 NLCD tile(s).
(Down)Loading NLCD tile: N36W108
Downloading file: https://prd-tnm.s3.amazonaws.com/StagedProducts/NLCD/data/2006/canopy/3x3/NLCD2006_CAN_N36W108.zip
Error in value[[3L]](cond) : 
  nlcd file C:\bryan\rscripts\goatscape\RAW\NLCD\NLCD2006_CAN_N36W108.zip corrupt or incomplete. Please delete the file and try again.

... 

I've tried various permutation and different input templates.  All receive the same error.

Any help or suggestions will be appreciated.  Thanks. Bryan

**Comment by bocinsky** [comment]
Hi. I don't think the canopy data is available from the National Map for 2001 or 2006. See here:
[https://prd-tnm.s3.amazonaws.com/index.html?prefix=StagedProducts/NLCD/data/2006/](https://prd-tnm.s3.amazonaws.com/index.html?prefix=StagedProducts/NLCD/data/2006/)

**Comment by bocinsky** [comment]
The 2001 canopy data have a different file naming convention. I've just pushed a fix, but please try and break it!

**Comment by willbmisled** [comment]
Kyle: thanks for looking into this so quickly.  I just reinstalled from github and now the 2001 canopy download works fine.  As you mentioned above, apparently the canopy data are not available for 2006 (https://www.mrlc.gov/nlcd06_data.php).  So that solves that problem.  I'll keep working with it.  Useful package.  Cheers.

**Comment by bocinsky** [comment]
Thanks! I'm going to close this for now. Please don't hesitate to let me know if you find any other bugs or would like to see other features. Cheers!
