### ISSUE TITLE
Make sure to git tag each CRAN release

### ISSUE THREAD

**Issue by sckott** [ropensci/FedData#39]
thanks!

**Comment by bocinsky** [comment]
Thanks for the reminder!

**Comment by sckott** [comment]
hi again, do you think you could paste in your release notes for each cran version released?  

right now you have entries like:

```
This is the 2.5.4 CRAN release of FedData.
```

Where ideally release notes have the news items for that version. e.g., https://github.com/ropensci/spocc/releases/tag/v0.8.0

**Comment by bocinsky** [comment]
Dang, that was a mistake. Will update.

Best,
Kyle
