### ISSUE TITLE
New NED tile names

### ISSUE THREAD

**Issue by salbeke** [ropensci/FedData#40]
It appears that perhaps the tile names have been changed to have the prefix of "USGS_NED_1" etc. At least that is what the files are names once downloaded from the National Map and the FedData package is returning an error saying the file is corrupt or doesn't exist.

**Comment by bocinsky** [comment]
Thanks for letting me know, Shannon! Their file names were in flux for a while, so hopefully they’ve settled on something consistent. I’ll look in to it in the next couple of days.

**Comment by bocinsky** [comment]
Hi there. The latest push should fix this issue, and I've added a new test. USGS is slowly updating all of its NED projects to integrate the latest LiDAR imagery. As tiles are updated, they switch to the new naming convention on the server. That means that I had to implement a fall back to file names without "USGS_NED_1" for those that have yet to be updated. @salbeke, would you mind checking to make sure my fix addresses the issue from your end? Then I'll close this and submit to CRAN.

**Comment by salbeke** [comment]
@bocinsky , I installed from github, ran my code that was failing and am happy to inform I was able to extract the dem as before the file naming changes. Thanks for the fix!

**Comment by bocinsky** [comment]
Thanks! Closing now. Should be on CRAN soon.
