### ISSUE TITLE
error when using get_nlcd for some counties

### ISSUE THREAD

**Issue by mikeyEcology** [ropensci/FedData#46]
Hi,
I'm using `get_nlcd` to extract data for over 3,000 counties in the USA over several years. For many of these counties, I get the following error: 

> Error in v[[i]] : subscript out of bounds
In addition: Warning messages:
1: In matrix(ratvalues, nrow = length(ratvalues)/length(ratnames)) :
  data length [2303] is not a sub-multiple or multiple of the number of rows [255]
2: In matrix(ratvalues, nrow = length(ratvalues)/length(ratnames)) :
  data length [2303] is not a sub-multiple or multiple of the number of rows [255]

While for most counties I do not have any problem. I'm providing some reproducible code, using a shapefile that can be downloaded [here](https://www.arcgis.com/home/item.html?id=3b69769aa9b646a483af81d05e7702d2), although I'm having this problem with another USA shapefile, so you might not need to download this file to produce the error. In this code, I'm assuming that you have unzipped the file and put the folder containing the shapefile in your working directory. 

`````
library(sf)
library(FedData)

# read in shapefile
shp <- read_sf("./USA_Counties_as_Shape/USA_Counties.shp")
which_fips <- "04001" # this FIPS code is not working, but if you try "04003" it will work
# subset shapefile for county of interest
sub_shp <- subset(shp, FIPS == which_fips)
# extract nlcd data
nlcd_data <- get_nlcd(as(sub_shp, 'Spatial'), 
                      label = which_fips, 
                      year = 2001) # 2001 does not work in this county, but if you set year = 2006 for this county the function works fine
`````

I'm using R Version 3.6.1. I'd appreciate any advice on this issue. Thank you in advance.

**Comment by bocinsky** [comment]
Hi there. Thanks for the detailed issue. 

There've been some problems with the NLCD tiles hosted on AWS (mainly missing tiles) that I'd been accessing for FedData, so I've actually gone ahead and just pushed a change to start using the [MRLC web coverage service](https://www.mrlc.gov/geoserver/ows?service=WCS&version=2.0.1&request=GetCapabilities) instead. The function parameters are a little different, but you should be able to get up and running very fast. Install from Github:

```r
install.packages("devtools")
devtools::install_github("ropensci/FedData")
```

Then have a look at the help file:
```r
?get_nlcd
```
for the new parameter options. Note that the function now writes to a temporary directory by default, rather than the working directory.

Your example should just work out of the box, though. I'll leave this open in case you still have trouble getting what you need.

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3
library(FedData)
#> Loading required package: sp

# read in shapefile
shp <- read_sf("~/Downloads/USA_Counties_as_Shape/USA_Counties.shp")
which_fips <- "04001" # this FIPS code is not working, but if you try "04003" it will work
# subset shapefile for county of interest
sub_shp <- subset(shp, FIPS == which_fips)
# extract nlcd data
nlcd_data <- get_nlcd(as(sub_shp, 'Spatial'), 
                      label = which_fips, 
                      year = 2001)
```

<sup>Created on 2019-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mikeyEcology** [comment]
Hi @bocinsky,
Thank you for getting back to me and for making this push. I was able to run the above code, but I got a new error when I tried to run the function in a different year. So if I run:
`
nlcd_data <- get_nlcd(as(sub_shp, 'Spatial'), 
                      label = which_fips, 
                      year = 2011)
`

I get the error:

> Error in .local(.Object, ...) : 
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file.

>

**Comment by bocinsky** [comment]
Hmm, it just worked fine for me. Two things:

- Just as a test, please try using `force.redo=TRUE`. If a download got canceled at some point, that would be a problem... it doesn't [yet] text the validity of previously downloaded files.
- `get_nlcd` now accepts simple features! No need to change to a `Spatial*` object.

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3
library(FedData)
#> Loading required package: sp

# read in shapefile
shp <- read_sf("~/Downloads/USA_Counties_as_Shape/USA_Counties.shp")
which_fips <- "04001" # this FIPS code is not working, but if you try "04003" it will work
# subset shapefile for county of interest
sub_shp <- subset(shp, FIPS == which_fips)
# extract nlcd data
get_nlcd(sub_shp, 
         label = which_fips, 
         year = 2011,
         force.redo = TRUE)
#> class      : RasterLayer 
#> dimensions : 16014, 3548, 56817672  (nrow, ncol, ncell)
#> resolution : 30, 30  (x, y)
#> extent     : -12245292, -12138852, 3958587, 4439007  (xmin, xmax, ymin, ymax)
#> crs        : +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs 
#> source     : memory
#> names      : NLCD_2011_Land_Cover_L48 
#> values     : 11, 95  (min, max)
```

<sup>Created on 2019-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mikeyEcology** [comment]
Thank you @bocinsky! This works. 
I think the problem might have been that I was using `as(sub_shp, 'Spatial')` as the template instead of simply `sub_shp`, as you suggested. After changing this, everything is running smoothly without specifying `force.redo = TRUE`. 
Thanks,
Mikey

**Comment by kendall-jefferys** [comment]
Hi @bocinsky 
I was getting a similar error, so I tried to I tried install.packages("devtools")
devtools::install_github("ropensci/FedData"), but now I get this error:

Error in get_nlcd(template = bbox, year = 2011, dataset = "canopy", label = "NLCD2011can", : No web coverage service at https://www.mrlc.gov/geoserver/mrlc_display/NLCD_2011_canopy_L48/ows. See available services at https://www.mrlc.gov/geoserver/ows?service=WCS&version=2.0.1&request=GetCapabilities

Do you know why this might be happening? Thanks!

**Comment by bocinsky** [comment]
Hey @kendall-jefferys ~

It looks like instead of "canopy", you have to specify "Tree_Canopy". The datasets available for each year are listed here: [https://www.mrlc.gov/geoserver/ows?service=WCS&version=2.0.1&request=GetCapabilities], though you have to go a ways down the page to get to them.

Try:
```r
get_nlcd(template = bbox, year = 2011, dataset = "Tree_Canopy", label = "NLCD2011can")
```

**Comment by bocinsky** [comment]
Hi @FLafont,

The NLCD data hosted on Amazon seems to not be working. Do try installing the dev version, like this:

```r
#install.packages("devtools")
devtools::install_github("ropensci/FedData")
```

And then run `get_nlcd` once more. Hope this helps!

KB
