### ISSUE TITLE
.rwl data with get_itrdb

### ISSUE THREAD

**Issue by luciadesoto** [ropensci/FedData#47]
Hi,
I am trying to download tree ring width data from the ITRDB with the get_itrdb function and I only get chronology data, even though if I select: 
   measurement.type = "Ring Width",
   chronology.type = "Measurements Only"
Please, let me know what I doing wrong.
Cheers,
Lucía

**Comment by bocinsky** [comment]
Hi Lucia. Thanks for your message. FedData does not yet enable access to the raw ring width series, but only to the chronologies. It's on my development list, but I haven't yet gotten around to it. the Measurement Type and Chronology Type categories are taken straight from the ITRDB readme... I know they can be a little deceiving. Sorry about that!

Best,
Kyle


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by luciadesoto** [comment]
Hi Kyle,
What a pity! I will wait for it :D
Thanks a lot for the other functions of the package.
Best,
Lucía




---- 
Lucía DeSoto, PhD
Marie Skłodowska-Curie PostDoctoral Fellow (IF)
at Spanish National Research Council (CSIC)
http://luciadesoto.wordpress.com/ <http://luciadesoto.wordpress.com/>
Estación Experimental de Zonas Áridas (EEZA-CSIC) <http://www.eeza.csic.es/en/default.aspx>
Ctra Sacramento s/n, La Cañada de San Urbano
E-04120 Almería, Spain
