### ISSUE TITLE
task 1 failed - "extents do not overlap"

### ISSUE THREAD

**Issue by dmontecino** [ropensci/FedData#49]
Hi Kyle:

I used the FedData to get nlcd for several States. Pretty cool. 

Now I am trying to download DAYMET data and, to be honest, I do not know why this problem is occurring but I thought it would be useful to check it is not the package. The script downloads the data, but at the time it starts to extract I get the error. I would really really appreciate if you could take a look. The error does not occur as a result of an obvious problem in one single tile.

Two things. I am using the package hosted in Github and secondly, there is a message in the nc's. I leave the script

```
library(rgdal)
library(gdalUtils)
library(raster)
library(maptools)
library(sp)
library(shapefiles)
library(devtools)
library(scales)
library(ncdf4)
library(FedData)

#Downloaded online from us census  https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html
states=readOGR("/your_path/", layer = "cb_2018_us_state_5m") #s

PA=states[states@data$STUSPS=="PA",]

plot(PA)

# The projection of the DAYMET data is presented here https://daac.ornl.gov/DAYMET/guides/Daymet_V3_CFMosaics.html#datacharact

lambert.conformal.conic <- CRS("+proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs")

PA.proj=spTransform(PA, lambert.conformal.conic)

test=get_daymet(template=PA.proj, 
                label = paste0("day_met", "PA"), 
                element="prcp",
                years = c(2010), 
                force.redo=T) #FedData package

test=nc_open("your_path_to_Files/RAW/DAYMET/11931/prcp.nc")
test
```

Check the test dimension characteristics. It says: "[1] 'vobjtovarid4: **** WARNING **** I was asked to get a varid for dimension named nv BUT this dimension HAS NO DIMVAR! Code will probably fail at this point'"

Thanks in advance

Diego

**Comment by bocinsky** [comment]
Hi Diego~

Thanks for bringing this to my attention. Apparently, something changed with the Daymet data I was downloading, and the projection of the rasters was all wacky — the projection of the downloaded data wasn't the same as the one you noted above. I am actually in the process of rewriting the whole codebase for FedData, so you caught this at a good time! I've updated the function in the development version... see below, and be sure to look at the new help file for some updated functionality.

Let me know if you have any more trouble, or find any more bugs!

Cheers,
Kyle

``` r
# install.packages("devtools")
# devtools::install_github("ropensci/FedData")
# devtools::install_cran("tigris")
# devtools::install_cran("mapview")

# Load the Penn. boundary from the US Census TIGRIS database
PA <- tigris::states(resolution = "5m",
                     class = "sf",
                     progress_bar = FALSE)
PA <- PA[PA$STUSPS == "PA",]

# Download precipitation for 2010
daymet_PA <- 
  FedData::get_daymet(template = PA,
                      label = "daymet_PA",
                      elements = "prcp",
                      years = 2010,
                      extraction.dir = ".",
                      progress = FALSE)
#> Loading required namespace: ncdf4

# Make a map
mapview::mapview(daymet_PA$prcp[[1]], 
                 na.color = NA,
                 layer.name = "DAYMET PRCP") + 
  mapview::mapview(PA, color = "white", 
                   col.regions = NA, 
                   alpha.regions = 0)
```

![](https://i.imgur.com/gUemeX7.png)

<sup>Created on 2020-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dmontecino** [comment]
works like a charm. Thanks!
