### ISSUE TITLE
get_itrdb()  -  Error in zips[[1]] : subscript out of bounds

### ISSUE THREAD

**Issue by vmanvailer** [ropensci/FedData#52]
Hi, I am trying to download the entire tree ring dataset using get_itrdb(). However, I am getting the error:

Error in zips[[1]] : subscript out of bounds

It seems that it is during the extraction. Can I fix this?

**Comment by bocinsky** [comment]
Hi. That can happen when a download is interrupted. I just ran both the CRAN and development version, and both worked. Try using `git_itrdb(force.redo = TRUE)`. If that doesn’t work, please post a reproducible example, and we can troubleshoot it together.

**Comment by bocinsky** [comment]
Hi. That can happen when a download is interrupted. I just ran both the CRAN and development version, and both worked. Try using `get_itrdb(force.redo = TRUE)`. If that doesn’t work, please post a reproducible example, and we can troubleshoot it together.

**Comment by vmanvailer** [comment]
Thank you!
I am new to posting my doubts, so forgive me if I leave something out.
Below is the code I am trying out with the error. I checked the downloaded files and the dataset seems to be complete.

```
library(FedData)
> get_itrdb(force.redo = TRUE)
Downloading file (if necessary): ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/chronologies/itrdb-v713-africa-crn.zip
Downloading file (if necessary): ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/chronologies/itrdb-v713-asia-crn.zip
Downloading file (if necessary): ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/chronologies/itrdb-v713-australia-crn.zip
Downloading file (if necessary): ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/chronologies/itrdb-v713-canada-crn.zip
Downloading file (if necessary): ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/chronologies/itrdb-v713-southamerica-crn.zip
Downloading file (if necessary): ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/chronologies/itrdb-v713-mexico-crn.zip
Downloading file (if necessary): ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/chronologies/itrdb-v713-europe-crn.zip
Downloading file (if necessary): ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/chronologies/itrdb-v713-usa-crn.zip
Error in zips[[1]] : subscript out of bounds
```

**Comment by vmanvailer** [comment]
I am using Rstudio with the R 3.6.3.
So I decided to try on base R and it worked. Don't understand why though.

**Comment by bocinsky** [comment]
Hmm, I don’t quite understand either, but I’m glad it worked. I’m going to close this for now, but if you continue having issues, please let me know!
