### ISSUE TITLE
get_ssurgo() returns error

### ISSUE THREAD

**Issue by kevinwolz** [ropensci/FedData#56]
```
WI025 <- get_ssurgo(template = "WI025", label = "WI_TEST")
```

Error: 'st_make_valid' is not an exported object from 'namespace:lwgeom'

**Comment by bocinsky** [comment]
Did you update to the latest version on GitHub?

`devtools::install_github(“ropensci/FedData”)`

**Comment by kevinwolz** [comment]
Oops. I did, but then forgot to reload the package. False alarm!
