### ISSUE TITLE
Error when trying to get_nlcd

### ISSUE THREAD

**Issue by mortiestmorty2020** [ropensci/FedData#58]
Hi everybody,

when I try to extract nlcd raster for my data with 
NLCD<-get_nlcd()
 
I get this error meassage:

Area of interest includes 1 NLCD tile(s).
(Down)Loading NLCD tile: N36W108
Downloading file: https://prd-tnm.s3.amazonaws.com/StagedProducts/NLCD/data/2006/landcover/3x3/NLCD2006_LC_N36W108.zip
Error in if (x == "" | x == ".") { : argument is of length zero

Anybody any clue?

**Comment by bocinsky** [comment]
Hey. The USGS removed the NLCD from the National Map AWS downloads, and so I've moved to the MRLC web coverage service in the development version of FedData. Install the development version like this:

```r
install.packages("devtools")
devtools::install_github("ropensci/FedData")
```

Then try running again, and you should be cooking with fire.

**Comment by mortiestmorty2020** [comment]
Hi Kyle! Thanks a lot for the spark! It worked! Much appreciated :)
