### ISSUE TITLE
cannot get NLCD data for bigger area (?)

### ISSUE THREAD

**Issue by mortiestmorty2020** [ropensci/FedData#59]
Hi,

when I try to get NLCD for a relatively small area, it works just fine:
For instance:
coords.x1	coords.x2	sample
-109.402	38.453	10443	
-109.402	38.453	10444	
-109.402	38.453	10445	
-109.402	38.453	10447	
-109.402	38.453	10448	
-109.790	38.552	10230	
-109.790	38.552	10316	
-109.790	38.552	10317	

however, when I add a collection point. Let's say:

-105.516	36.442	5995

I get this error:

"Fehler in curl::curl_fetch_disk(url, x$path, handle = handle) :
Send failure: Connection was reset"

NED in so forth works just fine, though.

What might be the issue here?

**Comment by mortiestmorty2020** [comment]
Correction...this error:

"Fehler in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Send failure: Connection was reset"

**Comment by bocinsky** [comment]
Hi @mortiestmorty2020. 

Sorry for the delay in getting to this. Can you send me the code you are using?

Best,
Kyle

**Comment by bocinsky** [comment]
Assuming that you are just sending a SpatialPointsDataFrame or simple features object with a points geom into `get_nlcd`, this will fail unless the points are close to one another. `get_nlcd` makes a request to the NLCD data services based on the bounding box of the requested object; adding a point far away makes the bounding box exceed the limitations of the service. I'd suggest cycling through your points and requesting each one in sequence. Let me know if that works for you.

**Comment by mortiestmorty2020** [comment]
Hi Kyle! Sorry for the late response...pretty busy theses days, but thanks for always answering so quickly! Appreciated! I think I was sending spatialpolygons created with sp. ...but I think it does not make any difference and your description of the problem makes sense. It works prefectly fine for elevation data for instance, but not for nlcd. Also, thanks for the recommended approach. I will try it soon and let you know if it worked for me. However, I have seen that there used to be a tile command for nlcd, just like for elevation data, but it seems not exist anymore, right?

**Comment by bocinsky** [comment]
That’s right. get_nlcd uses a WCS now.
