### ISSUE TITLE
get_ssurgo fails for non-us locale

### ISSUE THREAD

**Issue by bpatrzyk** [ropensci/FedData#61]
Hi, I have Polish locale configured on my system (pl_PL). 
I noticed that it affects dates parsing and leads to errors with downloading SSURGO files:
```
(Down)Loading SSURGO data for survey area 1 of 7: CO669
Downloading file: http://websoilsurvey.sc.egov.usda.gov/DSD/Download/Cache/SSA/wss_SSA_CO669_[NA].zip
Ostrzeżenie w poleceniu 'utils::unzip(file, exdir = tmpdir)':
  błąd 1 podczas rozpakowywania pliku zip
```
Notice the [NA] in the filename instead of the date. This is caused by the fact that with non-english locale `as.Date` with the `"%b %d %Y"` format cannot parse the month name from the `saverest` field.

I managed to overcome this problem by setting the locale manually in the R console:
```
Sys.setlocale("LC_TIME", 'en_US.UTF-8')
```

However, maybe it would be a good idea to wrap the calls to `as.Date` with the code that changes the locale temporarily?
For example:
```
currentTimeLocale<-Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME",  'en_US.UTF-8')
x<-as.Date("Jun  8 2020  5:12PM", format = "%b %d %Y")
Sys.setlocale("LC_TIME", currentTimeLocale)
```

**Comment by bocinsky** [comment]
Thanks for bringing this to my attention! I prefer not to have side effects like changing the users locale, if possible. So, instead I used `lubridate::parse_date_time` to specify the locale with which the date should be parsed. I just pushed an update here on Github... go ahead and give it a try.

**Comment by bpatrzyk** [comment]
Thanks for fixing it so quickly. I just checked it and it works! Your solution is much better than what I proposed - I've been looking for a conversion function that takes locale as an argument but I couldn't find any.
