### ISSUE TITLE
get_nlcd - corrupt or incomplete file warning

### ISSUE THREAD

**Issue by smurphy765** [ropensci/FedData#62]
Hello!

I am attempting to use the get_nlcd function, but am getting a warning about a corrupt or incomplete file. I am also getting a warning about a discarded datum in the coordinate reference system. At first, I thought this must be something with the template that I was using, but this error also appears when running the example code on the help page for 'get_nlcd.'

The full error returned is:

Area of interest includes 1 NLCD tile(s).
(Down)Loading NLCD tile: N36W108
Downloading file: https://prd-tnm.s3.amazonaws.com/StagedProducts/NLCD/data/2018/landcover/3x3/NLCD2018_LC_N36W108.zip
Error in value[[3L]](cond) : 
  nlcd file ~/Desktop/RAW/NLCD/NLCD2018_LC_N36W108.zip corrupt or incomplete. Please delete the file and try again.
In addition: Warning messages:
1: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum WGS_1984 in CRS definition,
 but +towgs84= values preserved
2: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum WGS_1984 in CRS definition,
 but +towgs84= values preserved
3: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings

**Comment by bocinsky** [comment]
Hey, I'm getting nlcd errors this morning as well. I'm looking into what's going on... it is possible that there has been some configuration changes on the NLCD WCS server.
