### ISSUE TITLE
Feature Request: Access the USGS GAP program dataset?

### ISSUE THREAD

**Issue by mattwilliamson13** [ropensci/FedData#65]
Hello,
Thanks for this amazing package. I'm wondering whether it would be possible to add the [USGS GAP datasets](https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis/gap) (species, land cover, and protected areas). I'm not sure whether it makes more sense to have a `get_gap` function with all of the options embedded within that function or something like a  `get_gap_padus` function for each of the data subsets, but I'd be happy to help try and integrate this functionality if it is of interest.

**Comment by bocinsky** [comment]
Hi! Thanks for the suggestion… I was recently made aware of the LANDFIRE data, and it is quite useful! I’ll add the GAP datasets to the list for future implementation!

Best,
Kyle

**Comment by mattwilliamson13** [comment]
Excellent - I'm happy to help, but i'm not entirely clear on how to handle the web service side to be able to restrict the data to the bounding box rather than the entire dataset. If you want some help and can point me to some resources describing the approach you'd prefer, I'm happy to give it a shot.
