### ISSUE TITLE
ESRI REST API Max Record Count

### ISSUE THREAD

**Issue by kbvernon** [ropensci/FedData#66]
Hi @bocinsky, I was fiddling with `FedData::get_wbd()` yesterday and was getting the same or a similar error as in #64. After some trial and error with your internal `esri_query()` function, it seems like the max record count is only a possible upper limit (in this case, 1000), and not one that will typically be reached in practice (I was getting the error around 700). Obviously, I can't rule out the possibility of user error. Still, any thoughts about, say, halving the max record count limit when you split the ids vector? I did not notice a significant drop in performance when I did this myself.

Cheers.

**Comment by bocinsky** [comment]
Hey, good sleuthing! I’ll give it a try… though it is disappointing that the maxRecordCount reported by the server wouldn’t be the actual maximum request! Halving seems sensible, in lieu of other solutions.

**Comment by bocinsky** [comment]
Worked like a charm for the NHD data! Closing now.

**Comment by kbvernon** [comment]
Awesome! Glad it helped!
