### ISSUE TITLE
get_ssurgo error

### ISSUE THREAD

**Issue by zbigski** [ropensci/FedData#69]
Heya,

sometime after downloading all files (.zip files are in 'RAW' directory), it is having some kind of aggregation error, has occurred in a couple different study areas

"Error: Can't combine `..1$constreeshrubgrp` <double> and `..2$constreeshrubgrp` <character>."

which seems related to some data encoding issue between different tabular or spatial files, any ideas? I have latest github feddata installed, R and R studio up to date...

**Comment by bocinsky** [comment]
hmmm. None off the top of my mind. Can you send me a reproducible code snippet so I can debug?

**Comment by zbigski** [comment]
thanks for the quick reply - sure, simplified a snippet below, main code used a few other packages in addition to those listed here, namely 'sp' for some area calculations, not sure if that could be an issue as well - any help is much appreciated!

# feddata - get_ssurgo debugging #

library(FedData)
library(tidycensus)
library(tidyverse)
library(tigris)
library(raster)
library(rasterVis)
library(oce)
library(rgeos)
library(sf)
library(tmap)

Name <- c("Atlanta" , "New York" ,"Phoenix"  ,"San Juan")
state_fips <- c("13" ,"36" ,"04", "72")
FIPS.Place.Code <- c( "04000", "51000", "55000", "76770")
test <- as.data.frame(cbind(Name,state_fips,FIPS.Place.Code))
rm(Name, state_fips,FIPS.Place.Code)

i<-1 # counter variable for loop

places <- places(test$state_fips[i], cb = TRUE, year = 2018, class = "sf") # get place (City) boundaries, need to get all place boundaries for a state and year


city <- places[grep(test$FIPS.Place.Code[i],places$PLACEFP),] # grab just the city of interest
rm(places) # get rid of statewide file

s <- st_bbox(city) # extract bounding coordinates and look up the UTM zone for the place using lonlat2utm fxn from OCE
utm.zone <- lonlat2utm(s[[1]],s[[2]])$zone # great

reference<-st_crs(city) # extract CRS for later use in plotting


city.t <- st_transform(city,CRS(paste0("+proj=utm +datum=NAD83 +zone=",utm.zone))) # get projected bounding box to pull NLCD raster data and other data sets
city.box <- polygon_from_extent(raster::extent(city.t), proj4string = paste0("+proj=utm +datum=NAD83 +zone=",utm.zone))

try(ssurgo <- get_ssurgo(template = city.box, label = name, raw.dir = "./RAW/SSURGO/",
                         extraction.dir = paste0("./EXTRACT/",name,"/SSURGO/"),
                         force.redo = FALSE)) # keeps throwing errors when combining files, slightly different errors for each study area

ssurgo <- get_ssurgo(template = city.box, label = name) # keeps throwing errors when combining files, slightly different errors for each study area




# end code snippet 

for the four different city study areas I was getting 3 different errors (NYC and ATL have same issue)

**Atlanta:**
"although coordinates are longitude/latitude, st_intersection assumes that they are planar
Error : Can't combine `..1$constreeshrubgrp` <character> and `..3$constreeshrubgrp` <double>.
In addition: Warning messages:
1: In if (class(template) != "character") { :
  the condition has length > 1 and only the first element will be used
2: attribute variables are assumed to be spatially constant throughout all geometries "

**New York:**
Error : Can't combine `..1$constreeshrubgrp` <double> and `..2$constreeshrubgrp` <character>.
In addition: Warning messages:
1: In if (class(template) != "character") { :
  the condition has length > 1 and only the first element will be used
2: attribute variables are assumed to be spatially constant throughout all geometries 

**Phoenix:**
"although coordinates are longitude/latitude, st_intersection assumes that they are planar
Error : Can't combine `..1$weg` <character> and `..4$weg` <double>."

**San Juan:**
"Error in do.call("rbind", .) : second argument must be a list
In addition: Warning messages:
1: attribute variables are assumed to be spatially constant throughout all geometries 
2: In get_ssurgo_inventory(template = template, raw.dir = raw.dir) :
  Some of the soil surveys in your area are unavailable.

            Soils and productivity data will have holes.

            Missing areas:
PR686PR689


            Continuing with processing available soils."

**Comment by bocinsky** [comment]
Thanks much for submitting that code... you've helped identify two bugs that I've never encountered before!

For Atlanta, New York, and Phoenix, FedData was attempting to guess column types in the SSURGO tabular data before combining tables across soil surveys. In the case of those three urban areas, it was guessing different column types for different surveys, which made `dplyr::bind_rows` throw an error. I've now changed the code so that type-guessing doesn't happen until after the tables are merged.

For San Juan, neither of the soil surveys have complete data in the SSURGO database. I hadn't contemplated a user selecting an area of interest with no complete soil surveys, but you've done it! (And I really should have contemplated it.) I've added a check that catches if no surveys exist, alerts the user, and returns a null value.

I've just pushed these changes. Reinstall from GitHub, and you should be good to go.

Here's a reprex that I used to test your use-case:

```r
    library(tidyverse)
    library(magrittr)
    library(FedData)
    library(tigris)

    get_city <- function(name, state){
      tigris::places(state, 
                     cb = TRUE, 
                     year = 2018, 
                     class = "sf",
                     progress_bar = FALSE) %>%
        tigris::filter_place(name)
    }

    list(
      cities = c("Atlanta" , "New York" ,"Phoenix"),
      states = c("GA" ,"NY" ,"AZ")
    ) %>%
      purrr::pmap(~get_city(.x,.y)) %>%
      do.call("rbind",.) %>%
      dplyr::select(NAME) %>%
      dplyr::rowwise() %>%
      dplyr::mutate(
        ssurgo = list(
          suppressMessages(
            get_ssurgo(
              template = geometry, 
              label = NAME, 
              raw.dir = "./RAW/SSURGO/",
              extraction.dir = paste0("./EXTRACT/",NAME,"/SSURGO/"),
              force.redo = FALSE
            )
          )
        )
      ) %>%
      sf::st_as_sf()
    #> Simple feature collection with 3 features and 2 fields
    #> geometry type:  MULTIPOLYGON
    #> dimension:      XY
    #> bbox:           xmin: -112.3241 ymin: 33.29026 xmax: -73.70002 ymax: 40.91758
    #> geographic CRS: NAD83
    #> # A tibble: 3 x 3
    #> # Rowwise: 
    #>   NAME                                                     geometry ssurgo      
    #>   <chr>                                          <MULTIPOLYGON [°]> <list>      
    #> 1 Atlanta (((-84.42855 33.65749, -84.42698 33.65761, -84.42701 33.… <named list…
    #> 2 New Yo… (((-73.77336 40.85945, -73.77244 40.85974, -73.77055 40.… <named list…
    #> 3 Phoenix (((-112.1263 33.36182, -112.1255 33.36305, -112.1176 33.… <named list…
```
<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
