### ISSUE TITLE
Error when using get_nlcd to get all of CONUS: Error in curl::curl_fetch_disk(url, x$path, handle = handle) : Empty reply from server

### ISSUE THREAD

**Issue by mickayla32** [ropensci/FedData#70]
Hi there,
I want to apologize first if this is a repeat question-- I'm having trouble getting the get_nlcd function to work, even after following suggestions in previous posts.

I'm trying to use get_nlcd to download the extent of the conterminous US. Here is my code:

I started by downloading the FedData package this way, as suggested in other posts:
`devtools::install_github("ropensci/FedData")
`

And `sessionInfo()` gives` FedData_3.0.0.9000`

I used this code to get my template area:
```
us <- ne_countries(continent = "North America", country = "United States of America", returnclass = "sf") %>%
  st_transform(crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80
+towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
```

And this is my get_nlcd function code:
```
nlcd <- get_nlcd(template = us,
                 label = "nlcd_2016",
                 year = 2016,
                 force.redo= TRUE)
```
Again, the error I'm getting is this: 
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Empty reply from server

I then tried your suggestion in [this post](https://github.com/ropensci/FedData/issues/67) ... Using this code:
```
site_df <- data.frame(city = c('Denver', 'Boulder'), 
                      lat = c(39.7392, 40.0150), 
                      lon = c(-104.9903, -105.2705))

site_df <- st_as_sf(site_df, 
                    coords = c("lon","lat"), 
                    crs = 4326)

# Get NLCD data for Denver example
nlcd <- get_nlcd(template = site_df,
                 label = "nlcd_2016",
                 year = 2016,
                 force.redo= TRUE)
```
and it seems to work! However, I'm trying to get a larger area...

I also saw in another [post](https://github.com/ropensci/FedData/issues/45) that you mentioned "there must be a limit to the size of the request you can back to the NLCD web coverage service"... 
Could this possibly be the problem? Is there no way to use get_nlcd to get the entire CONUS map?
Any suggestions?

**Comment by bocinsky** [comment]
Hi there~

I think you are running into the size limit problem. If you are interested in the entire CONUS, I’d recommend just downloading it from the MRLC dataset, here: https://www.mrlc.gov/data <https://www.mrlc.gov/data>. FedData is really about extracting subsets of these large federated datasets.

Best,
Kyle
