### ISSUE TITLE
The pal_nlcd function has been dropped

### ISSUE THREAD

**Issue by jsta** [ropensci/FedData#74]
Looks like the `pal_nlcd` function was dropped in https://github.com/ropensci/FedData/commit/634adad0dd3b7d431e1df8227d6cb39df3adb0aa Was this intentional?

**Comment by bocinsky** [comment]
Hey there. Sorry I took so long to respond to this. It was definitely intentional, but negligent. ;-) I'll add it back in ASAP.

**Comment by bocinsky** [comment]
It's back!
