### ISSUE TITLE
get_nlcd throwing error regardless of input used

### ISSUE THREAD

**Issue by oransom** [ropensci/FedData#76]
I'm trying to use `get_nlcd` to retrieve NLCD data for any dataset. I've got what I believe to be the newest FedData package (3.0.0.9000) and even when I use the vepPolygon example (shown below), I get the following error:

CODE SNIP:
> vepPolygon <- polygon_from_extent(raster::extent(672800, 740000, 4102000, 4170000),\
>                                   proj4string = "+proj=utm +datum=NAD83 +zone=12")
> NLCD <- get_nlcd(
>   template = vepPolygon,
>   year = 2016,
>   dataset = "landcover",
>   label = "VEPIIN"
> )

ERROR:
> Area of interest includes 1 NLCD tile(s).
> (Down)Loading NLCD tile: N36W108
> Downloading file: https://prd-tnm.s3.amazonaws.com/StagedProducts/NLCD/data/2016/landcover/3x3/NLCD2016_LC_N36W108.zip
> Error in value[[3L]](cond) : 
>   nlcd file /Users/R/r_test/Test1/RAW/NLCD/NLCD2016_LC_N36W108.zip corrupt or incomplete. Please delete the file and try again.
> In addition: Warning message:
> In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
>   spgeom1 and spgeom2 have different proj4 strings

The error persists if I use `force.redo = TRUE`, or any call variants I can think of. I have no issue getting the NED tiles with the same polygon. I've tried other polygons as well as sf's with always the same error. Am I doing something wrong or is the call for NLCD updated with release 3? R version 4.05, Mac OS X 11.2.3. 

Thanks for the help! NLCD is crucial to what I do - it'd be awesome to have this working

**Comment by bocinsky** [comment]
Hmm, it looks like you may still be using an outdated version (even though you are using the development version).

Get the latest version with 
devtools::install_github(“ropensci/FedData”)

And then the call will be a little different:

vepPolygon <- polygon_from_extent(raster::extent(672800, 740000, 4102000, 4170000), proj4string = "+proj=utm +datum=NAD83 +zone=12")
NLCD <- 
get_nlcd( 
	template = vepPolygon,
	year = 2016,
	dataset = "Land_Cover",
	label = "VEPIIN"
)

I just tested it, and it worked great!

Let me know if you have any other questions.

**Comment by oransom** [comment]
hmmm. Uninstall/Reinstall is giving me the same package (3.0.0.9000) - what is the most up to date version number? 

I get an error with the above code telling me to change "Land_Cover" to "landcover" which makes me think I'm on the wrong package perhaps, as you indicate...

**Comment by oransom** [comment]
Got it - Had to reinstall from CRAN and then from git. Don't know why this worked, but it did! Working! Thank you!

**Comment by bocinsky** [comment]
Great! Yeah, I haven’t been incrementing version numbers in the dev version, which may have been causing the problem. Glad it worked!

Best,
Kyle
