### ISSUE TITLE
library install issue..? 

### ISSUE THREAD

**Issue by CDorich** [ropensci/FedData#80]
I'm trying to follow the code [here](https://docs.ropensci.org/FedData/), trying to download SSURGO data and map the respective polygons that exist within a given shapefile. I try to run the exact code given in the link and am running into the following errors:      

       SSURGO.MEVE <- get_ssurgo(template = FedData::meve, label = "meve")      
Error: 'meve' is not an exported object from 'namespace:FedData'

similarly, 

     SSURGO.areas <- get_ssurgo(
       template = c("CO670", "CO075"),
        label = "CO_TEST") 

    SSURGO.areas.CO675 <-
     SSURGO.areas$spatial %>%
     dplyr::filter(AREASYMBOL == "CO075")

Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "c('SpatialPolygonsDataFrame', 'SpatialPolygons', 'Spatial', 'SpatialVector', 'SpatialPolygonsNULL')"

What do I have wrong? Or is there some sort of package issue?

**Comment by bocinsky** [comment]
Hi there. The Mesa Verde dataset is currently only available in the development version of FedData. Have you installed the development version?

Try:

```r
install.packages("devtools")
devtools::install_github("ropensci/FedData")

FedData::meve
#> Simple feature collection with 1 feature and 0 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -12084260 ymin: 4460933 xmax: -12060310 ymax: 4488079
#> Projected CRS: WGS 84 / Pseudo-Mercator
#> # A tibble: 1 x 1
#>                                                                         geometry
#>                                                                    <POLYGON [m]>
#> 1 ((-12069431 4488079, -12069195 4487868, -12068915 4487617, -12068915 4487616,…
```
