### ISSUE TITLE
Download issue with Daymet

### ISSUE THREAD

**Issue by nksingh01** [ropensci/FedData#84]
Hi there, 
First off, thanks a lot for such a neat package. I have been using it for a while without any issues. Recently, I used this package to get dayment data (North America) and for some reason I am getting error for 2020 year files only. I am not sure why the function doesn't recognizes the 2020 precip.nc file. 

#code used -
get_daymet(template=as(poly,"Spatial"),label=ws_bndry$Site[1],elements = c('prcp'),years = 2018:2020)

error message- 
Error in R_nc4_open: NetCDF: Unknown file format
Error in { : 
  task 1 failed - "task 3 failed - "Error in nc_open trying to open file 
/UsersDocuments/Daymet/RAW/DAYMET/11747/2020/prcp.nc""

**Comment by bocinsky** [comment]
Hi there! I'm glad you find the package useful. Something changed about the 2020 Daymet NetCDF files, but in the dev version of FedData I've moved to downloading the data from a web coverage service which ameliorates the problem. Install the dev version with:

```r
# install.packages("devtools")
dev tools::install_github("ropensci/FedData")
```

Hope that helps!
