### ISSUE TITLE
Cran version

### ISSUE THREAD

**Issue by glorious1** [ropensci/FedData#85]
I downloaded the CRAN version of FedData after reading about it here on Github.  It took me a couple of hours of floundering before I realized that the CRAN version (2.5.7) was significantly different from what I saw on Github.  FedData::meve didn't work and I couldn't use an sf object as a template.

So I installed instead the development version.  I was able to use it, but the function help in RStudio gives "Internal Server Error".

I'm using it to access NHD data.  I was glad to find it because using st_read with a wkt_filter on the national dataset returns an empty object.  It does work on the state-level datasets though.  Thank you for making this available.

**Comment by bocinsky** [comment]
You're welcome, and sorry for the delated response. I bet you found that restarting RStudio got the help files working correctly. I still haven't pushed the new version to CRAN, but hope to soon.
