### ISSUE TITLE
get_ned() errors: no NED tiles are available for your study area

### ISSUE THREAD

**Issue by KingaHill** [ropensci/FedData#86]
Hi Kyle,
This package is great and I have been able to access several valuable datasets but I'm running into a bump with the get_ned function.
I am trying to download the 1/3 arc second DEM and am getting an error that the tile does not exist when I know it exists because I can download it manually from the national map.

Here is my code (I can make a reproducible boundary if you need)

DEM13 <- FedData::get_ned(
  template = boundary,
  label = "norfolk_dem13",
  res = "13")

and the error:

Area of interest includes 1 NED tiles.
(Down)Loading NED tile for 37N and 77W.
Error in FedData::get_ned(template = boundary, label = "norfolk_dem13",  : 
  No NED tiles are available for your study area. Please check your input data and internet connection.

It says that 1 NED tile exists and then says that No NED tiles exist. I have no trouble downloading the 1 arc second tile (res = "1")

Thanks for any input

**Comment by bocinsky** [comment]
Hi there! USGS changed some paths, and it broke the 1/3 arc sec functionality. I've just pushed an update that should solve your problem. Can you check with your code and confirm?

**Comment by KingaHill** [comment]
Thank you so much for your quick action on this.
I removed the package and re-installed from github devtools::install_github("ropensci/FedData")

Your changes work and I was able to access the 1/3 arc second DEM.
Thank you!

**Comment by bocinsky** [comment]
Super! Closing this now.
