### ISSUE TITLE
get_nlcd() errors

### ISSUE THREAD

**Issue by timbean** [ropensci/FedData#87]
Having an issue downloading NLCD data using this function:

"Downloading file: https://prd-tnm.s3.amazonaws.com/StagedProducts/NLCD/data/2011/landcover/3x3/NLCD2011_LC_N39W123.zip ... NLCD2011_LC_ND9W123.zip corrupt or incomplete. Please delete the file and try again." 

These tiles do not appear to be hosted at the referenced URL any more? Same issue for other years (2006, 2001).

**Comment by bocinsky** [comment]
Hi there~

Yes, they've been gone for awhile. The dev version of FedData retrieves NLCD data from an updated source, but the CRAN version is still trying to get the old (unavailable) data. I suggest installing the dev version:

```r
install.packages("devtools")
devtools::install_github("ropensci/FedData")
```

Definitely have a look at the help docs for `get_nlcd`, as the function call might have changed, subtly.
