### ISSUE TITLE
Daymet omitting 31st of December in leap years

### ISSUE THREAD

**Issue by thechibo** [ropensci/FedData#89]
Hello,

I noticed that Daymet omits the 31st of December in leap years (2004, 2008, 2012, etc,). That is, it downloads the first 365 days of each year.

Best Regards,
John

**Comment by bocinsky** [comment]
Yep, Daymet uses a 365 day year, even in leap years. See documentation here: https://daac.ornl.gov/DAYMET/guides/Daymet_Daily_V4.html
