### ISSUE TITLE
get_nhd error depending on template

### ISSUE THREAD

**Issue by monikashea** [ropensci/FedData#90]
I am attempting to download NHD data for DuPage County, IL: 
`DuPage <- tigris::counties(state = "IL") %>% 
  dplyr::filter(NAME == "DuPage")`
`DuPage_water <- FedData::get_nhd(template = DuPage, label = "DuPage")`

But this results in the following error: 
`Error in split.default(x, ceiling(seq_along(x)/n)) : 
  first argument must be a vector`

This error does not occur when I repeat the above steps for other nearby counties, e.g.: 
`Cook <- tigris::counties(state = "IL") %>% 
  dplyr::filter(NAME == "Cook")`
`Cook_water <- FedData::get_nhd(template = Cook, label = "Cook")`

I dug into the FedData code and was unable to find this particular error written in. I see several sf functions are used in NHD_FUNCTIONS.R, so perhaps this error is occurring in one of those steps.

**Comment by bocinsky** [comment]
Thank you for this, and sorry for the delay. I just pushed a fix for it, but won’t be able to submit a patch to CRAN for a bit as I just recently submitted one (and the CRAN maintainers prefer infrequent submissions). Things should work for you if you install the dev version from here on GitHub. Thanks!
