### ISSUE TITLE
Coordinate Reference System: NA

### ISSUE THREAD

**Issue by KingaHill** [ropensci/FedData#91]
I have been using the FedData package for a few months with great enjoyment.
This morning I updated my R version to 4.2.2 and re-installed the FedData dev version pakage (devtools::install_github("ropensci/FedData"))

When I run my previously functional code to download NLCD raster

land_all <-
  FedData::get_nlcd(
    template = boundary,
    label = paste0(cityname),
    year = 2019
  )

I get a raster with no coordinate reference system. 

sf::st_crs(land_all)
Coordinate Reference System: NA

**Comment by KingaHill** [comment]
I installed the package rgdal and the error was fixed. Shouldn't that be a dependency?

**Comment by rhijmans** [comment]
Please do switch to "terra" if you can. "terra" is easier to use and much more powerful. "raster" is kept alive because of the many dependencies and existing scripts, but it is otherwise not actively developed.
