### ISSUE TITLE
Geting error when using FedData to download daymet data

### ISSUE THREAD

**Issue by gpzhu** [ropensci/FedData#92]
Hello
using FedData to get daymet data has an error, using polygon as mask.  could you have look? thanks
MI_daymet_select <- FedData::get_daymet(
  #--- supply the vector data in sp ---#
  template = as(MI_counties_select, "Spatial"),
  #--- label ---#
  label = "MI_counties_select",
  #--- variables to download ---#
  elements = c("prcp","tmax"),
  #--- years ---#
  years = 2000:2001 )
###########################
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'stack': Unknown dataset, [ornldaac/1840/daymet_v4_daily_na_tmin_2020.nc].

**Comment by bocinsky** [comment]
Thanks for this! the tempo codes changed on the Daymet threads server. Updated! Will submit patch to CRAN, hopefully today.
