### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [ropensci/FedData#94]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

Re #93 not even soft dependencies will help, I'm afraid; but if **terra** is available as a dependency of **raster**, **raster** will be happy.

**Comment by bocinsky** [comment]
Thanks @rsbivand, I'm on it!

**Comment by bocinsky** [comment]
This is fixed in 3.0.2, on its way to CRAN.
