### ISSUE TITLE
get_nlcd() leads to following error: "Error in curl::curl_fetch_disk(url, x$path, handle = handle) :    transfer closed with outstanding read data remaining"

### ISSUE THREAD

**Issue by Steve-Koller** [ropensci/FedData#97]
Hi there, I'm working on a remote computer that has fairly large RAM (>180GB). I've previously run the below code without issue, but today am receiving the error shown in the issue title. My goal is to read in the entire National Landcover Database data for the lower 48 states using the "get_nlcd()" operation. The shapefile object I am using as a template for cropping is a layer of all US census tracts in the lower 48 from "tidycensus," called "US_tracts_nowater." While my actual shapefile includes ~84k census tract features, this code is written to run on a sample subset of 8,500.

```
library(curl)

nlcd_list = list()

nrows = 100

Sys.time()
for (i in 1:85){
  
  nlcd_list[[i]] = get_nlcd(US_tracts_nowater[(nrows*(i-1)+1):(nrows*i),], 
                            year=2019,
                            label = "label",
                            dataset = c("landcover"),
                            landmass = "L48",
                            raster.options = c("COMPRESS=DEFLATE", "ZLEVEL=9"),
                            force.redo = FALSE)
  
  
  nlcd_list[[i]] = terra::rast(nlcd_list[[i]]) # convert to SpatRaster objects

  
  print(i)
}
Sys.time()
```

**Error message I receive:**
"Error in curl::curl_fetch_disk(url, x$path, handle = handle) :    transfer closed with outstanding read data remaining"

After running the above script and receiving the above error, I re-run the same script a second time and the "nlcd_list" list is produced and the error does not show. The nlcd_list has 85 items and is 111 KB in size. However, when trying to merge the items in the list using either of the below methods, my R session aborts (despite the fact that I successfully ran this exact script yesterday and my RAM limit is at least an order of magnitude greater than what the operations in this case use). 

```
1.  merged = do.call(merge,nlcd_list)
```
and
```
2. rsrc = sprc(nlcd_list)

merged = merge(rsrc)
```

Does anyone have an idea what the problem is/problems are? Any recommendations for how to avoid this error and successfully merge would be much appreciated. Thank you.

**Comment by Rapsodia86** [comment]
Hi there, could you attach the shapefile?

**Comment by Steve-Koller** [comment]
I tried uploading a zip with the shapefile, but it was too large for GitHub (>25MB). Below is the original code I used to pull the file from tidycensus if that helps. Also, as an aside, I am working on a remote server on which system RAM is communal, and was just informed that a colleague is running a large job that is using a particularly large share of the common RAM. This could also be an issue, but still uncertain. Will follow up with updates on that in case my experience can help inform other users down the road. 

```
library(tidycensus)
US_tracts = get_acs(geography = "tract", variables = c(population = "B01001_001"),
        state = states, year = 2020, geometry = TRUE, output="wide")
```

**Comment by Rapsodia86** [comment]
What do you have under "states"?

**Comment by Steve-Koller** [comment]
Yes, thank you. Script for "states" object below.

```
states = c("AL", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "ID", "IL", "IN", "IA", "KS",
            "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY",
            "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV",
            "WI", "WY")
```

**Comment by bocinsky** [comment]
Hi @Steve-Koller. We recently reverted back to the "official" NLCD web coverage service, and my guess is that service had a hiccup yesterday that aborted one of the `get_nlcd` calls. The NLCD WCS is proving to be a lot more finicky than the same data that I'd self-hosted as a series of COGs on a Google Cloud bucket. Perhaps first try and run again using `force.redo = FALSE`. Also, FWIW, using `label = "label"` as you do above will reload data from the first time in the session that you run `get_nlcd`. Definitely give each of your groups of census tracts a different name, so that you can be assured you are downloading the correct data.

**Comment by bocinsky** [comment]
(And thanks for the back and forth between you two, @Rapsodia86! I'm diving into a different issue at the moment.)

**Comment by Rapsodia86** [comment]
@Steve-Koller In my case, there was no curl error and data were downloaded so it must have been your server issue, 
But following your code:

```
library(tidycensus)
library(FedData)
library(curl)
states <- c("AL", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "ID", "IL", "IN", "IA", "KS",
                     "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY",
                     "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV",
                     "WI", "WY")
US_tracts = get_acs(geography = "tract", variables = c(population = "B01001_001"),
                    state = states, year = 2020, geometry = TRUE, output="wide")
nlcd_list = list()
nrows = 100

for (i in 1:85){
  nlcd_list[[i]] = get_nlcd(US_tracts[(nrows*(i-1)+1):(nrows*i),], 
                            year=2019,
                            label = "label",
                            dataset = c("landcover"),
                            landmass = "L48",
                            raster.options = c("COMPRESS=DEFLATE", "ZLEVEL=9"),
                            force.redo = FALSE)
  
  
  nlcd_list[[i]] = terra::rast(nlcd_list[[i]]) # convert to SpatRaster objects 
  print(i)
}
```
I am getting 85 identical rasters?
```
> nlcd_list[[1]]
class       : SpatRaster 
dimensions  : 17461, 10817, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : 708735, 1033245, 848745, 1372575  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source      : label_NLCD_Land_Cover_2019.tif 
categories  : Class, Color, Description 
name        :                        Class 
min value   :                   Open Water 
max value   : Emergent Herbaceous Wetlands 

> nlcd_list[[74]]
class       : SpatRaster 
dimensions  : 17461, 10817, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : 708735, 1033245, 848745, 1372575  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source      : label_NLCD_Land_Cover_2019.tif 
categories  : Class, Color, Description 
name        :                        Class 
min value   :                   Open Water 
max value   : Emergent Herbaceous Wetlands 
```

**Comment by bocinsky** [comment]
Alright, I'm going to close this for now under the assumption that it was an isolated issue, but feel free to open it again if I'm wrong.

**Comment by Steve-Koller** [comment]
Hi @bocinsky @Rapsodia86 thank you for your help, it's much appreciated. I'm running the script on my personal machine now, and the error is no longer showing, so guessing this is a server issue, but still ironing that out.  

To the point about identical rasters, thank you. I've tweaked the script to add an "i" after each label to uniquely identify each group in the loop. Below is script running on a subset. I think this addresses the identical raster problem.

```
nrows = 1000
Sys.time()
for (i in 1:6){
  
  nlcd_list[[i]] = get_nlcd(US_tracts[(nrows*(i-1)+1):(nrows*i),], 
                            year=2019,
                            label = paste0("TractGroup_", i, ""),
                            dataset = c("landcover"),
                            landmass = "L48",
                            raster.options = c("COMPRESS=DEFLATE", "ZLEVEL=9"),
                            force.redo = FALSE)
  
  nlcd_list[[i]] = terra::rast(nlcd_list[[i]])
  
  print(i)
}
Sys.time()

rsrc = sprc(nlcd_list)

merged = merge(rsrc)

plot(merged)
```

**Comment by Rapsodia86** [comment]
Yeap, it is ok now. Glad it works!
