### ISSUE TITLE
Error (down)Loading GHCN station data

### ISSUE THREAD

**Issue by ndichistan** [ropensci/FedData#99]
I am having trouble downloading data using the "get_ghcn_daily" function. Every attempt to download ghcn data including the default "meve" data results in Error. The stations are identified, but then there's an error downloading the data for the station. I also observed that I could not access the ftp page that the function tries to download the data from. Could you look into this.

**Comment by bocinsky** [comment]
Fixed by switching to NCEI's https file servers... FTP service was disabled.

**Comment by ndichistan** [comment]
Hi @bocinsky. Thanks for the help. 
However, I tried the new version and got a series of errors and a warning message at the end without downloading any data still. I have attached an excerpt of the warning and error message. I have also attached the code. 

##error
"Error (down)Loading GHCN station data for station USW00093983
(Down)Loading GHCN station data for station USW00093987
Downloading file: https://www.ncei.noaa.gov/pub/data/ghcn/daily/all/USW00093987.dly
Error (down)Loading GHCN station data for station USW00093987
Warning messages:
1: attribute variables are assumed to be spatially constant throughout all geometries 
2: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 1: C:\Users\ndichi\AppData\Local\Temp\Rtmpk5sfq6\FedData\extractions\ghcn\ghcn_BBTx/ghcn_BBTx_GHCN_stations.shp does not appear to be a file or directory."

##code
`ghcn_BBTx<-get_ghcn_daily(template=station_coord, label="ghcn_BBTx",
                          elements="PRCP", force.redo = T)`

[station_cord.txt](https://github.com/ropensci/FedData/files/11576912/station_cord.txt)

**Comment by bocinsky** [comment]
Ugh! The file format on the http server changed just enough to screw with things. I've implemented a correction, and am testing now. Reopening this! Thank you!

**Comment by ndichistan** [comment]
> Ugh! The file format on the http server changed just enough to screw with things. I've implemented a correction, and am testing now. Reopening this! Thank you!

Any updates regarding this?

**Comment by bocinsky** [comment]
Sorry, should have closed this. I pushed changes to Github last week that fix the issue, but am holding off on CRAN submission for now. Please install the dev version:

```r
# install.packages("remotes")
remotes::install_github("ropensci/FedData")
```

I'll close this now.
